In [1]:
import numpy as np

size = int(input("Enter the size of the array: "))

Enter the size of the array:  5


In [4]:
print("1. Single-dimensional array:")
arr = np.array((1, 2, 3, 4))
print(arr)

1. Single-dimensional array:
[1 2 3 4]


In [5]:
print("2. Multi-dimensional array:")
arr2= np.array( [ [1, 0], [6, 4] ] )
print(arr2)

2. Multi-dimensional array:
[[1 0]
 [6 4]]


In [6]:
print("3. Array of all ones:")
arr3 = np.ones(size)
print(arr3)

3. Array of all ones:
[1. 1. 1. 1. 1.]


In [7]:
print("4. Array of all zeros:")
arr4= np.zeros(size)
print(arr4)


4. Array of all zeros:
[0. 0. 0. 0. 0.]


In [9]:
print("5. Array with random values:")
num1= float(input("Enter minimum value: "))
num2 = float(input("Enter maximum value: "))
random_array = np.random.rand(size) * (num2 - num1) + num1
print(random_array)


5. Array with random values:


Enter minimum value:  2
Enter maximum value:  12


[ 5.16224859 11.05932952  4.048104    7.93487184  3.80380517]


In [10]:
array = np.random.randint(10, size=(20)) 
# the array will be having 20 elements. 
print(array)

[8 1 9 1 1 0 8 5 5 1 8 4 0 4 7 9 8 7 0 2]


In [ ]:
print("\n6. Diagonal matrix:")
num= float(input("Enter the diagonal value"))
D = np.diag(num)
print(D)


6. Diagonal matrix:
