In [ ]:
------- QUES6 ----------

In [13]:
import numpy as np
arr1 = np.random.randint(50, size=(5,5))
arr1


array([[ 1, 32,  0, 11, 19],
       [10, 40, 19, 31, 36],
       [ 1, 19,  0,  7, 30],
       [18,  9, 19, 21, 49],
       [46, 17, 38, 44, 30]])

In [14]:
arr2 = np.random.randint(50, size=(5,5))
arr2


array([[15, 13, 39, 31, 42],
       [35, 11, 14,  1, 34],
       [32, 24, 21,  4, 36],
       [ 0, 24,  7,  6, 34],
       [47, 46, 22,  7, 39]])

In [15]:
#Addition
add = arr1+arr2
add

array([[16, 45, 39, 42, 61],
       [45, 51, 33, 32, 70],
       [33, 43, 21, 11, 66],
       [18, 33, 26, 27, 83],
       [93, 63, 60, 51, 69]])

In [16]:
#Multiplocation
mul = arr1*arr2
mul

array([[  15,  416,    0,  341,  798],
       [ 350,  440,  266,   31, 1224],
       [  32,  456,    0,   28, 1080],
       [   0,  216,  133,  126, 1666],
       [2162,  782,  836,  308, 1170]])

In [21]:
#Division
div1 = arr1/arr2
div1

C:\Users\CSLab\AppData\Local\Temp\ipykernel_9152\3575137442.py:2: RuntimeWarning: divide by zero encountered in true_divide
  div1 = arr1/arr2


array([[ 0.06666667,  2.46153846,  0.        ,  0.35483871,  0.45238095],
       [ 0.28571429,  3.63636364,  1.35714286, 31.        ,  1.05882353],
       [ 0.03125   ,  0.79166667,  0.        ,  1.75      ,  0.83333333],
       [        inf,  0.375     ,  2.71428571,  3.5       ,  1.44117647],
       [ 0.9787234 ,  0.36956522,  1.72727273,  6.28571429,  0.76923077]])

In [22]:
div2 = arr2/arr1
div2

C:\Users\CSLab\AppData\Local\Temp\ipykernel_9152\3383509860.py:1: RuntimeWarning: divide by zero encountered in true_divide
  div2 = arr2/arr1


array([[15.        ,  0.40625   ,         inf,  2.81818182,  2.21052632],
       [ 3.5       ,  0.275     ,  0.73684211,  0.03225806,  0.94444444],
       [32.        ,  1.26315789,         inf,  0.57142857,  1.2       ],
       [ 0.        ,  2.66666667,  0.36842105,  0.28571429,  0.69387755],
       [ 1.02173913,  2.70588235,  0.57894737,  0.15909091,  1.3       ]])

In [27]:
#Exponential
exp1 = arr1**arr2
exp1



array([[          1,           0,           0,  1823198243,   492349961],
       [          0,           0,  -281002215,          31,           0],
       [          1,  1938398561,           0,        2401,           0],
       [          1,   -88328767,   893871739,    85766121, -1641169055],
       [          0,  -867578399,  1312817152,  1450229760,           0]],
      dtype=int32)

In [28]:
exp2 = arr2**arr1
exp2

array([[         15,  1780897921,           1,   129082719,  1332215808],
       [ 1528444521,  1640444129,  1052246016,           1,           0],
       [         32,           0,           1,       16384,           0],
       [          0,   402653184,   442181591,  1449132032,           0],
       [ -512419231,   -13762560,           0, -1924013279, -1606643183]],
      dtype=int32)

In [44]:
name = "Saloni"
age = 19
address = "Delhi"

In [ ]:

#Display
print("My name is ",name)
print("My age is ",age)
print("I live in ",address)

